import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case simplifiedChinese
    case traditionalChinese
    case english

    var id: String { rawValue }

    var nativeTitle: String {
        switch self {
        case .simplifiedChinese: return "简体中文"
        case .traditionalChinese: return "繁體中文"
        case .english: return "English"
        }
    }
}

struct Localizer {
    let language: AppLanguage

    func text(_ key: String) -> String {
        Self.table[key]?[language] ?? Self.table[key]?[.simplifiedChinese] ?? key
    }

    private static let table: [String: [AppLanguage: String]] = [
        "overview": [.simplifiedChinese: "概览", .traditionalChinese: "概覽", .english: "Overview"],
        "sensors": [.simplifiedChinese: "传感器", .traditionalChinese: "感測器", .english: "Sensors"],
        "strategy": [.simplifiedChinese: "策略", .traditionalChinese: "策略", .english: "Strategy"],
        "power": [.simplifiedChinese: "电源", .traditionalChinese: "電源", .english: "Power"],
        "safety": [.simplifiedChinese: "安全与权限", .traditionalChinese: "安全與權限", .english: "Safety"],
        "currentPreset": [.simplifiedChinese: "当前预设", .traditionalChinese: "目前預設", .english: "Preset"],
        "monitoring": [.simplifiedChinese: "监控中", .traditionalChinese: "監控中", .english: "Monitoring"],
        "controlling": [.simplifiedChinese: "控制中", .traditionalChinese: "控制中", .english: "Controlling"],
        "strategySwitching": [.simplifiedChinese: "切换策略…", .traditionalChinese: "切換策略…", .english: "Switching…"],
        "strategyActive": [.simplifiedChinese: "策略已生效", .traditionalChinese: "策略已生效", .english: "Strategy Active"],
        "restoreAuto": [.simplifiedChinese: "恢复自动", .traditionalChinese: "恢復自動", .english: "Restore Auto"],
        "restoreAppleAuto": [.simplifiedChinese: "恢复 Apple 自动控制", .traditionalChinese: "恢復 Apple 自動控制", .english: "Restore Apple Auto"],
        "openFanPilot": [.simplifiedChinese: "打开 FanPilot", .traditionalChinese: "開啟 FanPilot", .english: "Open FanPilot"],
        "quit": [.simplifiedChinese: "退出", .traditionalChinese: "結束", .english: "Quit"],
        "language": [.simplifiedChinese: "语言", .traditionalChinese: "語言", .english: "Language"],
        "currentPresetMenu": [.simplifiedChinese: "当前预设", .traditionalChinese: "目前預設", .english: "Preset"],

        "automatic": [.simplifiedChinese: "自动", .traditionalChinese: "自動", .english: "Auto"],
        "quiet": [.simplifiedChinese: "静音", .traditionalChinese: "靜音", .english: "Quiet"],
        "low": [.simplifiedChinese: "低速", .traditionalChinese: "低速", .english: "Low"],
        "medium": [.simplifiedChinese: "中速", .traditionalChinese: "中速", .english: "Medium"],
        "high": [.simplifiedChinese: "高速", .traditionalChinese: "高速", .english: "High"],
        "full": [.simplifiedChinese: "全速", .traditionalChinese: "全速", .english: "Full"],

        "daily": [.simplifiedChinese: "日常办公", .traditionalChinese: "日常辦公", .english: "Daily"],
        "externalDisplay": [.simplifiedChinese: "外接显示器", .traditionalChinese: "外接顯示器", .english: "External Display"],
        "heavyLoad": [.simplifiedChinese: "高负载", .traditionalChinese: "高負載", .english: "Heavy Load"],
        "manualFull": [.simplifiedChinese: "手动全速", .traditionalChinese: "手動全速", .english: "Manual Full"],
        "custom": [.simplifiedChinese: "自定义", .traditionalChinese: "自訂", .english: "Custom"],

        "all": [.simplifiedChinese: "全部", .traditionalChinese: "全部", .english: "All"],
        "cpu": [.simplifiedChinese: "CPU", .traditionalChinese: "CPU", .english: "CPU"],
        "battery": [.simplifiedChinese: "电池", .traditionalChinese: "電池", .english: "Battery"],
        "enclosure": [.simplifiedChinese: "机身", .traditionalChinese: "機身", .english: "Enclosure"],
        "wireless": [.simplifiedChinese: "无线", .traditionalChinese: "無線", .english: "Wireless"],
        "storage": [.simplifiedChinese: "存储", .traditionalChinese: "儲存", .english: "Storage"],
        "other": [.simplifiedChinese: "其他", .traditionalChinese: "其他", .english: "Other"],

        "fans": [.simplifiedChinese: "风扇", .traditionalChinese: "風扇", .english: "Fans"],
        "fanRPMSubtitle": [.simplifiedChinese: "最低 / 当前 / 最大 RPM", .traditionalChinese: "最低 / 目前 / 最高 RPM", .english: "Minimum / Current / Maximum RPM"],
        "controlSensor": [.simplifiedChinese: "主控传感器", .traditionalChinese: "主控感測器", .english: "Control Sensor"],
        "sensorSubtitle": [.simplifiedChinese: "选择一个传感器作为策略主控", .traditionalChinese: "選擇一個感測器作為策略主控", .english: "Choose one sensor for strategy control"],
        "search": [.simplifiedChinese: "搜索", .traditionalChinese: "搜尋", .english: "Search"],
        "sensorColumn": [.simplifiedChinese: "传感器", .traditionalChinese: "感測器", .english: "Sensor"],
        "temperature": [.simplifiedChinese: "温度", .traditionalChinese: "溫度", .english: "Temperature"],
        "usage": [.simplifiedChinese: "用途", .traditionalChinese: "用途", .english: "Use"],
        "primary": [.simplifiedChinese: "主控", .traditionalChinese: "主控", .english: "Primary"],

        "safetySubtitle": [.simplifiedChinese: "控制风扇需要本地 helper 与管理员授权", .traditionalChinese: "控制風扇需要本機 helper 與管理員授權", .english: "Fan control requires a local helper and admin authorization"],
        "coolingModes": [.simplifiedChinese: "散热档位", .traditionalChinese: "散熱檔位", .english: "Cooling Modes"],
        "status": [.simplifiedChinese: "状态", .traditionalChinese: "狀態", .english: "Status"],
        "helperStatus": [.simplifiedChinese: "Helper 状态", .traditionalChinese: "Helper 狀態", .english: "Helper"],
        "smcAccess": [.simplifiedChinese: "SMC 访问", .traditionalChinese: "SMC 存取", .english: "SMC Access"],
        "lastWrite": [.simplifiedChinese: "最后写入", .traditionalChinese: "最後寫入", .english: "Last Write"],
        "hardwareMode": [.simplifiedChinese: "硬件模式", .traditionalChinese: "硬體模式", .english: "Hardware Mode"],
        "detectAppleSMC": [.simplifiedChinese: "检测 AppleSMC", .traditionalChinese: "偵測 AppleSMC", .english: "Detect AppleSMC"],
        "enableFanControl": [.simplifiedChinese: "启用风扇控制", .traditionalChinese: "啟用風扇控制", .english: "Enable Fan Control"],
        "installUpdateHelper": [.simplifiedChinese: "安装/更新授权 helper", .traditionalChinese: "安裝/更新授權 helper", .english: "Install/Update Helper"],
        "runDiagnostics": [.simplifiedChinese: "运行诊断", .traditionalChinese: "執行診斷", .english: "Run Diagnostics"],
        "scanFanKeys": [.simplifiedChinese: "扫描风扇 Key", .traditionalChinese: "掃描風扇 Key", .english: "Scan Fan Keys"],
        "testTargetRPM": [.simplifiedChinese: "测试目标转速", .traditionalChinese: "測試目標轉速", .english: "Test Target RPM"],
        "testModeKey": [.simplifiedChinese: "测试模式 Key", .traditionalChinese: "測試模式 Key", .english: "Test Mode Key"],
        "testMinimumRPM": [.simplifiedChinese: "测试最低转速", .traditionalChinese: "測試最低轉速", .english: "Test Minimum RPM"],
        "testForceControl": [.simplifiedChinese: "测试强制控制", .traditionalChinese: "測試強制控制", .english: "Test Force Control"],
        "advancedDiagnostics": [.simplifiedChinese: "高级诊断", .traditionalChinese: "進階診斷", .english: "Advanced Diagnostics"],
        "advancedDiagnosticsSubtitle": [.simplifiedChinese: "用于排查 SMC key 与写入方式，日常使用通常不需要打开。", .traditionalChinese: "用於排查 SMC key 與寫入方式，日常使用通常不需要開啟。", .english: "Tools for troubleshooting SMC keys and write paths. Usually not needed for daily use."],
        "uninstallHelper": [.simplifiedChinese: "卸载 helper", .traditionalChinese: "卸載 helper", .english: "Uninstall Helper"],
        "diagnostics": [.simplifiedChinese: "SMC 诊断", .traditionalChinese: "SMC 診斷", .english: "SMC Diagnostics"],
        "controlEnabledTitle": [.simplifiedChinese: "风扇控制已启用", .traditionalChinese: "風扇控制已啟用", .english: "Fan Control Enabled"],
        "writeRestrictedTitle": [.simplifiedChinese: "AppleSMC 可读，写入受限", .traditionalChinese: "AppleSMC 可讀，寫入受限", .english: "AppleSMC Readable, Write Restricted"],
        "smcAvailableTitle": [.simplifiedChinese: "AppleSMC 已可访问", .traditionalChinese: "AppleSMC 已可存取", .english: "AppleSMC Available"],
        "helperNeededTitle": [.simplifiedChinese: "需要管理员授权 helper", .traditionalChinese: "需要管理員授權 helper", .english: "Admin Helper Required"],
        "monitorOnlyTitle": [.simplifiedChinese: "当前为监控模式", .traditionalChinese: "目前為監控模式", .english: "Monitoring Mode"],
        "controlEnabledBody": [.simplifiedChinese: "FanPilot 正在按策略评估散热档位。", .traditionalChinese: "FanPilot 正在依策略評估散熱檔位。", .english: "FanPilot is evaluating cooling modes from your strategy."],
        "writeRestrictedBody": [.simplifiedChinese: "FanPilot 已经能读取温度和风扇转速，但当前系统拒绝写入风扇控制 key。应用会保持监控模式。", .traditionalChinese: "FanPilot 已能讀取溫度與風扇轉速，但目前系統拒絕寫入風扇控制 key。應用會保持監控模式。", .english: "FanPilot can read temperatures and fan speed, but macOS rejected fan-control writes. The app will remain in monitoring mode."],
        "smcAvailableBody": [.simplifiedChinese: "FanPilot 已经能读取 AppleSMC。你可以先在概览页查看真实温度和转速。", .traditionalChinese: "FanPilot 已能讀取 AppleSMC。你可以先在概覽頁查看真實溫度與轉速。", .english: "FanPilot can read AppleSMC. You can inspect real temperatures and fan speed on the overview page."],
        "helperNeededBody": [.simplifiedChinese: "macOS 已拒绝普通进程访问 AppleSMC。下一步需要安装本地授权 helper 后再读取和控制风扇。", .traditionalChinese: "macOS 已拒絕一般程序存取 AppleSMC。下一步需要安裝本機授權 helper 後再讀取與控制風扇。", .english: "macOS denied regular AppleSMC access. Install the local authorized helper before reading and controlling fans."],
        "monitorOnlyBody": [.simplifiedChinese: "FanPilot 可以读取温度和风扇转速，但尚未控制风扇。", .traditionalChinese: "FanPilot 可以讀取溫度與風扇轉速，但尚未控制風扇。", .english: "FanPilot can monitor temperatures and fan speed, but fan control is not enabled."],
        "safetyNotice": [.simplifiedChinese: "首次启用或更新时，FanPilot 会安装一个本地授权 helper；已安装可用时会直接复用，并通过它访问 AppleSMC。FanPilot 只会提高最低风扇转速，不会低于 Apple 默认最低值；任何读取或写入失败都会自动回到监控模式。", .traditionalChinese: "首次啟用或更新時，FanPilot 會安裝一個本機授權 helper；已安裝可用時會直接沿用，並透過它存取 AppleSMC。FanPilot 只會提高最低風扇轉速，不會低於 Apple 預設最低值；任何讀取或寫入失敗都會自動回到監控模式。", .english: "On first enable or update, FanPilot installs a local authorized helper. When a usable helper is already installed, FanPilot reuses it to access AppleSMC. FanPilot only raises fan speed targets and never goes below Apple defaults. Any read or write failure returns the app to monitoring mode."],
        "strategySubtitle": [.simplifiedChinese: "根据一个主控传感器自动切换散热档位", .traditionalChinese: "根據一個主控感測器自動切換散熱檔位", .english: "Switch cooling modes from one control sensor"],
        "strategyName": [.simplifiedChinese: "策略名称", .traditionalChinese: "策略名稱", .english: "Strategy Name"],
        "presetNameLocked": [.simplifiedChinese: "预设策略不支持重命名；请选择“自定义”创建个性名称。", .traditionalChinese: "預設策略不支援重新命名；請選擇「自訂」建立個人名稱。", .english: "Preset strategies cannot be renamed. Choose Custom to use a personal name."],
        "temperatureRules": [.simplifiedChinese: "温度规则", .traditionalChinese: "溫度規則", .english: "Temperature Rules"],
        "temperatureRulesHint": [.simplifiedChinese: "按从低到高的阈值匹配；低温可设为自动或静音。", .traditionalChinese: "依由低到高的門檻匹配；低溫可設為自動或靜音。", .english: "Matched from low to high thresholds. Low temperatures can use Auto or Quiet."],
        "addRule": [.simplifiedChinese: "新增规则", .traditionalChinese: "新增規則", .english: "Add Rule"],
        "mode": [.simplifiedChinese: "档位", .traditionalChinese: "檔位", .english: "Mode"],
        "deleteRule": [.simplifiedChinese: "删除规则", .traditionalChinese: "刪除規則", .english: "Delete Rule"],
        "advanced": [.simplifiedChinese: "高级设置", .traditionalChinese: "進階設定", .english: "Advanced"],
        "hysteresis": [.simplifiedChinese: "回落温差", .traditionalChinese: "回落溫差", .english: "Hysteresis"],
        "minimumHold": [.simplifiedChinese: "最短保持时间", .traditionalChinese: "最短保持時間", .english: "Minimum Hold"],
        "samplingInterval": [.simplifiedChinese: "采样间隔", .traditionalChinese: "取樣間隔", .english: "Sampling Interval"],
        "emergencyFull": [.simplifiedChinese: "紧急全速温度", .traditionalChinese: "緊急全速溫度", .english: "Emergency Full Speed"],
        "restoreOnQuit": [.simplifiedChinese: "退出应用时恢复 Apple 自动控制", .traditionalChinese: "結束應用時恢復 Apple 自動控制", .english: "Restore Apple auto control on quit"],
        "restoreAfterWake": [.simplifiedChinese: "睡眠唤醒后恢复自动并重新评估策略", .traditionalChinese: "睡眠喚醒後恢復自動並重新評估策略", .english: "Restore auto and reevaluate after wake"],
        "restoreDailyDefaults": [.simplifiedChinese: "恢复日常办公默认值", .traditionalChinese: "恢復日常辦公預設值", .english: "Restore Daily Defaults"],
        "restorePresetDefaults": [.simplifiedChinese: "恢复 %@ 默认值", .traditionalChinese: "恢復 %@ 預設值", .english: "Restore %@ Defaults"],
        "saveStrategy": [.simplifiedChinese: "保存策略", .traditionalChinese: "儲存策略", .english: "Save Strategy"],
        "strategySaved": [.simplifiedChinese: "已保存", .traditionalChinese: "已儲存", .english: "Saved"],
        "seconds": [.simplifiedChinese: "秒", .traditionalChinese: "秒", .english: "sec"],

        "power.subtitle": [.simplifiedChinese: "电池、充电器与 macOS 电源设置", .traditionalChinese: "電池、充電器與 macOS 電源設定", .english: "Battery, charger, and macOS power settings"],
        "power.refresh": [.simplifiedChinese: "刷新", .traditionalChinese: "重新整理", .english: "Refresh"],
        "power.loading": [.simplifiedChinese: "正在读取系统电源报告…", .traditionalChinese: "正在讀取系統電源報告…", .english: "Loading system power report…"],
        "power.loadFailed": [.simplifiedChinese: "无法读取电源信息", .traditionalChinese: "無法讀取電源資訊", .english: "Unable to load power information"],
        "power.updated": [.simplifiedChinese: "更新于", .traditionalChinese: "更新於", .english: "Updated"],
        "power.showSerial": [.simplifiedChinese: "显示电池序列号", .traditionalChinese: "顯示電池序號", .english: "Show battery serial number"],
        "power.hideSerial": [.simplifiedChinese: "隐藏电池序列号", .traditionalChinese: "隱藏電池序號", .english: "Hide battery serial number"],
        "power.modelInformation": [.simplifiedChinese: "型号信息", .traditionalChinese: "型號資訊", .english: "Model Information"],
        "power.chargeInformation": [.simplifiedChinese: "电量信息", .traditionalChinese: "電量資訊", .english: "Charge Information"],
        "power.healthInformation": [.simplifiedChinese: "效能信息", .traditionalChinese: "效能資訊", .english: "Health Information"],
        "power.acPowerSettings": [.simplifiedChinese: "交流电源设置", .traditionalChinese: "交流電源設定", .english: "AC Power Settings"],
        "power.batteryPowerSettings": [.simplifiedChinese: "电池电源设置", .traditionalChinese: "電池電源設定", .english: "Battery Power Settings"],
        "power.hardwareConfiguration": [.simplifiedChinese: "硬件配置", .traditionalChinese: "硬體設定", .english: "Hardware Configuration"],
        "power.chargerInformation": [.simplifiedChinese: "交流充电器信息", .traditionalChinese: "交流充電器資訊", .english: "AC Charger Information"],
        "power.scheduledEvents": [.simplifiedChinese: "计划的电源事件", .traditionalChinese: "排程的電源事件", .english: "Scheduled Power Events"],
        "power.serialNumber": [.simplifiedChinese: "序列号", .traditionalChinese: "序號", .english: "Serial Number"],
        "power.manufacturer": [.simplifiedChinese: "生产企业", .traditionalChinese: "製造商", .english: "Manufacturer"],
        "power.deviceName": [.simplifiedChinese: "设备名称", .traditionalChinese: "裝置名稱", .english: "Device Name"],
        "power.packLotCode": [.simplifiedChinese: "包装批次代码", .traditionalChinese: "包裝批次代碼", .english: "Pack Lot Code"],
        "power.pcbLotCode": [.simplifiedChinese: "PCB 批次代码", .traditionalChinese: "PCB 批次代碼", .english: "PCB Lot Code"],
        "power.firmwareVersion": [.simplifiedChinese: "固件版本", .traditionalChinese: "韌體版本", .english: "Firmware Version"],
        "power.hardwareRevision": [.simplifiedChinese: "硬件校正", .traditionalChinese: "硬體修訂", .english: "Hardware Revision"],
        "power.cellRevision": [.simplifiedChinese: "电池校正", .traditionalChinese: "電池修訂", .english: "Cell Revision"],
        "power.currentPowerSource": [.simplifiedChinese: "当前电源", .traditionalChinese: "目前電源", .english: "Current Power Source"],
        "power.lowWarning": [.simplifiedChinese: "电池电量低于警告水平", .traditionalChinese: "電池電量低於警告層級", .english: "Below Warning Level"],
        "power.fullyCharged": [.simplifiedChinese: "已充满电", .traditionalChinese: "已充飽電", .english: "Fully Charged"],
        "power.isCharging": [.simplifiedChinese: "正在充电", .traditionalChinese: "正在充電", .english: "Charging"],
        "power.fullChargeCapacity": [.simplifiedChinese: "全负荷容量 (mAh)", .traditionalChinese: "完全充電容量 (mAh)", .english: "Full Charge Capacity (mAh)"],
        "power.stateOfCharge": [.simplifiedChinese: "充电状态 (%)", .traditionalChinese: "充電狀態 (%)", .english: "State of Charge"],
        "power.chargeState": [.simplifiedChinese: "供电状态", .traditionalChinese: "供電狀態", .english: "Power State"],
        "power.timeRemaining": [.simplifiedChinese: "预计剩余时间", .traditionalChinese: "預估剩餘時間", .english: "Time Remaining"],
        "power.cycleCount": [.simplifiedChinese: "循环计数", .traditionalChinese: "循環計數", .english: "Cycle Count"],
        "power.condition": [.simplifiedChinese: "状态", .traditionalChinese: "狀態", .english: "Condition"],
        "power.systemSleepTimer": [.simplifiedChinese: "系统睡眠定时器", .traditionalChinese: "系統睡眠計時器", .english: "System Sleep Timer"],
        "power.diskSleepTimer": [.simplifiedChinese: "磁盘睡眠定时器", .traditionalChinese: "磁碟睡眠計時器", .english: "Disk Sleep Timer"],
        "power.displaySleepTimer": [.simplifiedChinese: "显示器睡眠定时器", .traditionalChinese: "顯示器睡眠計時器", .english: "Display Sleep Timer"],
        "power.wakeOnACChange": [.simplifiedChinese: "交流电变化时唤醒", .traditionalChinese: "交流電變化時喚醒", .english: "Wake on AC Change"],
        "power.wakeOnClamshellOpen": [.simplifiedChinese: "翻盖打开时唤醒", .traditionalChinese: "掀蓋時喚醒", .english: "Wake on Lid Open"],
        "power.wakeOnLAN": [.simplifiedChinese: "局域网唤醒", .traditionalChinese: "區域網路喚醒", .english: "Wake on LAN"],
        "power.dimBeforeSleep": [.simplifiedChinese: "睡眠前调暗显示器", .traditionalChinese: "睡眠前調暗顯示器", .english: "Dim Display Before Sleep"],
        "power.hibernateMode": [.simplifiedChinese: "Hibernate Mode", .traditionalChinese: "Hibernate Mode", .english: "Hibernate Mode"],
        "power.lowPowerMode": [.simplifiedChinese: "低电量模式", .traditionalChinese: "低耗電模式", .english: "Low Power Mode"],
        "power.networkPriority": [.simplifiedChinese: "网络可达性优先于睡眠", .traditionalChinese: "網路連線優先於睡眠", .english: "Prioritize Network Reachability"],
        "power.upsInstalled": [.simplifiedChinese: "UPS 已安装", .traditionalChinese: "UPS 已安裝", .english: "UPS Installed"],
        "power.connected": [.simplifiedChinese: "已连接", .traditionalChinese: "已連接", .english: "Connected"],
        "power.wattage": [.simplifiedChinese: "功率 (W)", .traditionalChinese: "功率 (W)", .english: "Wattage (W)"],
        "power.chargingPower": [.simplifiedChinese: "充电功率", .traditionalChinese: "充電功率", .english: "Charging Power"],
        "power.chargerName": [.simplifiedChinese: "充电器名称", .traditionalChinese: "充電器名稱", .english: "Charger Name"],
        "power.scheduledEvent": [.simplifiedChinese: "计划事件", .traditionalChinese: "排程事件", .english: "Scheduled Event"],
        "power.yes": [.simplifiedChinese: "是", .traditionalChinese: "是", .english: "Yes"],
        "power.no": [.simplifiedChinese: "否", .traditionalChinese: "否", .english: "No"],
        "power.normal": [.simplifiedChinese: "正常", .traditionalChinese: "正常", .english: "Normal"],
        "power.charging": [.simplifiedChinese: "正在充电", .traditionalChinese: "正在充電", .english: "Charging"],
        "power.charged": [.simplifiedChinese: "已充满", .traditionalChinese: "已充飽", .english: "Charged"],
        "power.discharging": [.simplifiedChinese: "使用电池", .traditionalChinese: "使用電池", .english: "On Battery"],
        "power.acPower": [.simplifiedChinese: "交流电源", .traditionalChinese: "交流電源", .english: "AC Power"],
        "power.batteryPower": [.simplifiedChinese: "电池电源", .traditionalChinese: "電池電源", .english: "Battery Power"]
    ]
}
